In [1]:
import numpy as np

In [2]:
import torch

In [3]:
f = torch.nn.Tanh()

In [7]:
x = torch.tensor([100])
x

tensor([100])

In [8]:
t1 = f(x)
t2 = f(f(x))
t3 = f(f(f(x)))
t4 = f(f(f(f(x))))

In [9]:
t1

tensor([1.])

In [10]:
t2

tensor([0.7616])

In [12]:
f4 = (1 - t4 ** 2) * t3
f4

tensor([0.4361])

In [13]:
f3 = (1 - t4 ** 2) * (1 - t3 ** 2) * t2

In [14]:
f2 = (1 - t4 ** 2) * (1 - t3 ** 2) * (1 - t2 ** 2) * t1

In [15]:
f1 = (1 - t4 ** 2) * (1 - t3 ** 2) * (1 - t2 ** 2) * (1 - t1 ** 2) * 100

In [16]:
f1, f2, f3, f4

(tensor([0.]), tensor([0.1677]), tensor([0.3041]), tensor([0.4361]))

In [17]:
f = torch.nn.ReLU()

In [18]:
t1 = f(x)
t2 = f(f(x))
t3 = f(f(f(x)))
t4 = f(f(f(f(x))))

In [19]:
torch.tensor([100]), t1, t2, t3

(tensor([100]), tensor([100]), tensor([100]), tensor([100]))