In [1]:
import torch

In [2]:
input_images = torch.tensor([[[[0,  1,  2],
                               [3,  4,  5],
                               [6,  7,  8]],
                              
                              [[9, 10, 11],
                               [12, 13, 14],
                               [15, 16, 17]],
                              
                              [[18, 19, 20],
                               [21, 22, 23],
                               [24, 25, 26]]],
                             
                             
                             [[[27, 28, 29],
                               [30, 31, 32],
                               [33, 34, 35]],
                              
                              [[36, 37, 38],
                               [39, 40, 41],
                               [42, 43, 44]],
                              
                              [[45, 46, 47],
                               [48, 49, 50],
                               [51, 52, 53]]]])

In [3]:
input_images

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]]],


        [[[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]],

         [[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44]],

         [[45, 46, 47],
          [48, 49, 50],
          [51, 52, 53]]]])

In [10]:
x = torch.zeros([input_images.shape[0],
                 input_images.shape[1],
                 input_images.shape[2] + 2,
                 input_images.shape[3] + 2]).int()
for i in range(input_images.shape[0]):
  for j in range(input_images.shape[1]):
    for k in range(input_images.shape[2]):
      for l in range(input_images.shape[3]):
        x[i][j][k + 1][l + 1] = input_images[i][j][k][l]
x

tensor([[[[ 0,  0,  0,  0,  0],
          [ 0,  0,  1,  2,  0],
          [ 0,  3,  4,  5,  0],
          [ 0,  6,  7,  8,  0],
          [ 0,  0,  0,  0,  0]],

         [[ 0,  0,  0,  0,  0],
          [ 0,  9, 10, 11,  0],
          [ 0, 12, 13, 14,  0],
          [ 0, 15, 16, 17,  0],
          [ 0,  0,  0,  0,  0]],

         [[ 0,  0,  0,  0,  0],
          [ 0, 18, 19, 20,  0],
          [ 0, 21, 22, 23,  0],
          [ 0, 24, 25, 26,  0],
          [ 0,  0,  0,  0,  0]]],


        [[[ 0,  0,  0,  0,  0],
          [ 0, 27, 28, 29,  0],
          [ 0, 30, 31, 32,  0],
          [ 0, 33, 34, 35,  0],
          [ 0,  0,  0,  0,  0]],

         [[ 0,  0,  0,  0,  0],
          [ 0, 36, 37, 38,  0],
          [ 0, 39, 40, 41,  0],
          [ 0, 42, 43, 44,  0],
          [ 0,  0,  0,  0,  0]],

         [[ 0,  0,  0,  0,  0],
          [ 0, 45, 46, 47,  0],
          [ 0, 48, 49, 50,  0],
          [ 0, 51, 52, 53,  0],
          [ 0,  0,  0,  0,  0]]]], dtype=torch.int32)

In [32]:
x.shape

torch.Size([2, 3, 5, 5])

In [11]:
kernel = torch.tensor([[[[0., 1, 0],
                         [1,  2, 1],
                         [0,  1, 0]],

                        [[1, 2, 1],
                         [0, 3, 3],
                         [0, 1, 10]],

                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]]]])

In [29]:
kernel.shape

torch.Size([1, 3, 3, 3])

In [14]:
def calc_out_shape(input_matrix_shape, out_channels, kernel_size, stride, padding):
    batch_size, channels_count, input_height, input_width = input_matrix_shape
    output_height = (input_height + 2 * padding - (kernel_size - 1) - 1) // stride + 1
    output_width = (input_width + 2 * padding - (kernel_size - 1) - 1) // stride + 1

    return batch_size, out_channels, output_height, output_width  

In [23]:
out_shape = calc_out_shape(x.shape, kernel.shape[0], kernel.shape[1], 1, 0)
out_shape

(2, 1, 3, 3)

In [26]:
y = torch.zeros(out_shape)
y

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [52]:
for i in range(out_shape[0]):
  for j in range(out_shape[1]):
    for k in range(out_shape[2]):
      for l in range(out_shape[3]):
        print((x[i, :, k * 1 : k * 1 + kernel.shape[2], l * 1 : l * 1 + kernel.shape[3]] * kernel).sum())
        y[i, j, k, l] = (x[i, :, k * 1 : k * 1 + kernel.shape[2], l * 1 : l * 1 + kernel.shape[3]] * kernel).sum()

tensor(1493.)
tensor(2148.)
tensor(1327.)
tensor(2202.)
tensor(3163.)
tensor(1975.)
tensor(1358.)
tensor(1963.)
tensor(1282.)
tensor(3788.)
tensor(5253.)
tensor(3163.)
tensor(5226.)
tensor(7294.)
tensor(4486.)
tensor(3113.)
tensor(4393.)
tensor(2848.)


In [53]:
y

tensor([[[[1493., 2148., 1327.],
          [2202., 3163., 1975.],
          [1358., 1963., 1282.]]],


        [[[3788., 5253., 3163.],
          [5226., 7294., 4486.],
          [3113., 4393., 2848.]]]])

In [34]:
a = torch.tensor([[ 0,  0,  0,  0,  0],
                  [ 0,  0,  1,  2,  0],
                  [ 0,  3,  4,  5,  0],
                  [ 0,  6,  7,  8,  0],
                  [ 0,  0,  0,  0,  0]])

In [35]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 1, 2, 0],
        [0, 3, 4, 5, 0],
        [0, 6, 7, 8, 0],
        [0, 0, 0, 0, 0]])

In [36]:
a.shape

torch.Size([5, 5])

In [38]:
a[0:3, 0:3]

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 3, 4]])

In [47]:
for img in x:
  b = img[:, 0:3, 0:3]
  c = (b * kernel).sum()
  print(c)

tensor(1493.)
tensor(3788.)


In [56]:
a = torch.zeros([6, 6])
a

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [59]:
b = torch.tensor([[2., 1, 1], [1, 2, 1], [1, 1, 2]])
b

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [61]:
for i in range(2):
  for j in range(2):
    a[3 * i : 3 * i + 3, 3 * j : 3 * j + 3] = b
a

tensor([[2., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 2., 1.],
        [1., 1., 2., 1., 1., 2.],
        [2., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 2., 1.],
        [1., 1., 2., 1., 1., 2.]])

In [62]:
a.flatten()

tensor([2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.,
        2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2.])

In [63]:
l = torch.zeros([a.shape[0], a.shape[1] + 1])

In [65]:
l[:a.shape[0], :a.shape[1]] = a

In [66]:
l

tensor([[2., 1., 1., 2., 1., 1., 0.],
        [1., 2., 1., 1., 2., 1., 0.],
        [1., 1., 2., 1., 1., 2., 0.],
        [2., 1., 1., 2., 1., 1., 0.],
        [1., 2., 1., 1., 2., 1., 0.],
        [1., 1., 2., 1., 1., 2., 0.]])

In [70]:
l.flatten(start_dim=0)

tensor([2., 1., 1., 2., 1., 1., 0., 1., 2., 1., 1., 2., 1., 0., 1., 1., 2., 1.,
        1., 2., 0., 2., 1., 1., 2., 1., 1., 0., 1., 2., 1., 1., 2., 1., 0., 1.,
        1., 2., 1., 1., 2., 0.])

In [71]:
for i in l:
  print(i)

tensor([2., 1., 1., 2., 1., 1., 0.])
tensor([1., 2., 1., 1., 2., 1., 0.])
tensor([1., 1., 2., 1., 1., 2., 0.])
tensor([2., 1., 1., 2., 1., 1., 0.])
tensor([1., 2., 1., 1., 2., 1., 0.])
tensor([1., 1., 2., 1., 1., 2., 0.])


In [72]:
kernel = torch.tensor(
                      [[[[0., 1, 0],
                         [1,  2, 1],
                         [0,  1, 0]],

                        [[1, 2, 1],
                         [0, 3, 3],
                         [0, 1, 10]],

                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]]]])

In [77]:
converted_kernel = kernel.flatten(start_dim=1)

In [80]:
converted_kernel

tensor([[ 0.,  1.,  0.,  1.,  2.,  1.,  0.,  1.,  0.,  1.,  2.,  1.,  0.,  3.,
          3.,  0.,  1., 10., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])