In [1]:
!pip install torch

In [2]:
import torch

In [3]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
torch.ones(3, 4, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
torch.Tensor([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [8]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [9]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [10]:
x.size()

torch.Size([3, 4])

In [11]:
x.shape

torch.Size([3, 4])

In [12]:
x[0]

tensor([1., 2., 3., 4.])

In [13]:
x[1]

tensor([5., 6., 7., 8.])

In [14]:
x[0, 0]

tensor(1.)

In [15]:
x[:, 0]

tensor([1., 5., 9.])

In [16]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [17]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [18]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [19]:
y

tensor([[12., 11., 10.,  9.],
        [ 8.,  7.,  6.,  5.],
        [ 4.,  3.,  2.,  1.]])

In [20]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [21]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [22]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [23]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [24]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [25]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [26]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [27]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [28]:
(x > 3).to(torch.uint8)

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [29]:
mask = x > 3

In [30]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [31]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [32]:
mask1 = (x > 3).to(torch.uint8)

In [33]:
x[mask1]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:30.)
  """Entry point for launching an IPython kernel.


tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [34]:
(x > 3).int()

tensor([[0, 0, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [35]:
y = x

In [36]:
y[0, 0] = 999

In [37]:
x

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [38]:
y

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [39]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [40]:
y = x.clone()

In [41]:
y[0, 0] = 999

In [42]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [43]:
y

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [44]:
x.dtype

torch.float32

In [45]:
x = x.double()

In [46]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)

In [47]:
x = x.int()

In [48]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)

In [49]:
x = x.float()

In [50]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [51]:
import numpy as np

In [52]:
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])

In [53]:
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [54]:
x = torch.from_numpy(x)

In [55]:
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [56]:
x = x.numpy()

In [57]:
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [58]:
x = torch.rand([20000, 30000])

In [59]:
x

tensor([[1.3375e-01, 8.7374e-01, 1.7176e-01,  ..., 6.1838e-01, 2.1471e-01,
         4.4834e-01],
        [1.2499e-04, 1.3017e-01, 9.8925e-01,  ..., 7.8222e-01, 1.4527e-01,
         5.7984e-01],
        [1.9629e-01, 7.9685e-01, 5.6931e-01,  ..., 1.5564e-01, 8.7485e-01,
         4.2135e-01],
        ...,
        [5.0943e-01, 5.8832e-01, 7.7865e-01,  ..., 7.0984e-01, 5.2831e-02,
         5.8463e-01],
        [4.5348e-01, 9.3474e-02, 9.7721e-01,  ..., 2.0335e-02, 3.0588e-01,
         9.0008e-01],
        [1.2357e-01, 6.6179e-01, 9.4435e-01,  ..., 3.0278e-01, 1.7945e-02,
         5.2942e-01]])

In [60]:
torch.cuda.is_available()

True

In [61]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [62]:
torch.device('cpu')

device(type='cpu')

In [63]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [64]:
device

device(type='cuda', index=0)

In [65]:
x_cuda = x.to(device)

In [66]:
x_cuda

tensor([[1.3375e-01, 8.7374e-01, 1.7176e-01,  ..., 6.1838e-01, 2.1471e-01,
         4.4834e-01],
        [1.2499e-04, 1.3017e-01, 9.8925e-01,  ..., 7.8222e-01, 1.4527e-01,
         5.7984e-01],
        [1.9629e-01, 7.9685e-01, 5.6931e-01,  ..., 1.5564e-01, 8.7485e-01,
         4.2135e-01],
        ...,
        [5.0943e-01, 5.8832e-01, 7.7865e-01,  ..., 7.0984e-01, 5.2831e-02,
         5.8463e-01],
        [4.5348e-01, 9.3474e-02, 9.7721e-01,  ..., 2.0335e-02, 3.0588e-01,
         9.0008e-01],
        [1.2357e-01, 6.6179e-01, 9.4435e-01,  ..., 3.0278e-01, 1.7945e-02,
         5.2942e-01]], device='cuda:0')

In [67]:
%time
y = (x - x + x * 10.0) ** 2

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 9.3 µs


In [68]:
%time
y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 8.58 µs


In [69]:
y

tensor([[1.7890e+00, 7.6343e+01, 2.9500e+00,  ..., 3.8240e+01, 4.6102e+00,
         2.0101e+01],
        [1.5623e-06, 1.6944e+00, 9.7861e+01,  ..., 6.1187e+01, 2.1103e+00,
         3.3622e+01],
        [3.8529e+00, 6.3497e+01, 3.2412e+01,  ..., 2.4223e+00, 7.6537e+01,
         1.7753e+01],
        ...,
        [2.5952e+01, 3.4612e+01, 6.0630e+01,  ..., 5.0388e+01, 2.7912e-01,
         3.4180e+01],
        [2.0564e+01, 8.7373e-01, 9.5494e+01,  ..., 4.1352e-02, 9.3560e+00,
         8.1015e+01],
        [1.5270e+00, 4.3797e+01, 8.9181e+01,  ..., 9.1677e+00, 3.2202e-02,
         2.8029e+01]])

In [70]:
y_cuda

tensor([[1.7890e+00, 7.6343e+01, 2.9500e+00,  ..., 3.8240e+01, 4.6102e+00,
         2.0101e+01],
        [1.5623e-06, 1.6944e+00, 9.7861e+01,  ..., 6.1187e+01, 2.1103e+00,
         3.3622e+01],
        [3.8529e+00, 6.3497e+01, 3.2412e+01,  ..., 2.4223e+00, 7.6537e+01,
         1.7753e+01],
        ...,
        [2.5952e+01, 3.4612e+01, 6.0630e+01,  ..., 5.0388e+01, 2.7912e-01,
         3.4180e+01],
        [2.0564e+01, 8.7373e-01, 9.5494e+01,  ..., 4.1352e-02, 9.3560e+00,
         8.1015e+01],
        [1.5270e+00, 4.3797e+01, 8.9181e+01,  ..., 9.1677e+00, 3.2202e-02,
         2.8029e+01]], device='cuda:0')